run.err: *** ERROR: (gringo): std::bad_alloc\nTraceback (most recent call last):\n File "/home/ubuntu/volume/width-based-algos-LAPKT/BFWS-sampling-bloom_partitioned/tarski-version/bfws_ste.py", line 124, in <module>\n args.sample_factor, args.sample_type)\n File "/home/ubuntu/volume/width-based-algos-LAPKT/BFWS-sampling-bloom_partitioned/tarski-version/bfws_ste.py", line 24, in main\n ground_generate_task( domain_file, problem_file, task)\n File "/home/ubuntu/volume/width-based-algos-LAPKT/BFWS-sampling-bloom_partitioned/tarski-version/tarski_parser/tarski_util.py", line 186, in ground_generate_task\n reachable_action_params = copy.deepcopy( grounding.ground_actions())\n File "/home/ubuntu/Applications/tarski/src/tarski/grounding/lp_grounding.py", line 39, in ground_actions\n model = self._solve_lp()\n File "/home/ubuntu/Applications/tarski/src/tarski/grounding/lp_grounding.py", line 50, in _solve_lp\n model_filename = run_clingo(lp)\n File "/home/ubuntu/Applications/tarski/src/tarski/reachability/clingo_wrapper.py", line 26, in run_clingo\n raise ExternalCommandError("Gringo exited with code {}".format(retcode))\ntarski.errors.ExternalCommandError: Gringo exited with code 1\n
