ERROR:root:message
Traceback (most recent call last):
  File "tarski_test.py", line 32, in main
    status = ground_generate_task( domain_file, problem_file, None, verbose, lenient)
  File "/home/anubhav-cs/Github/tarski-tests/tarski_util.py", line 101, in ground_generate_task
    read_problem( domain_file, problem_file)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/fstrips.py", line 43, in read_problem
    self.parse_domain(domain)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/fstrips.py", line 53, in parse_domain
    self.parse_file(filename, 'domain')
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/fstrips.py", line 50, in parse_file
    self.parser.visit(domain_parse_tree)
  File "/usr/local/lib/python3.7/dist-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/_fstrips/parser/parser.py", line 803, in accept
    return visitor.visitDomain(self)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/_fstrips/parser/visitor.py", line 19, in visitDomain
    return self.visitChildren(ctx)
  File "/usr/local/lib/python3.7/dist-packages/antlr4/tree/Tree.py", line 44, in visitChildren
    childResult = c.accept(self)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/_fstrips/parser/parser.py", line 959, in accept
    return visitor.visitRequireDef(self)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/_fstrips/reader.py", line 83, in visitRequireDef
    process_requirements(self.requirements, self.language)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/_fstrips/common.py", line 35, in process_requirements
    theories.load_theory(lang, Theory.ARITHMETIC)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/theories.py", line 61, in load_theory
    loader(lang)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/theories.py", line 77, in load_arithmetic_theory
    ite_func = lang.function('ite', lang.Object, lang.Object, lang.Object)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/fol.py", line 265, in function
    self._check_name_not_defined(name, self._functions, err.DuplicateFunctionDefinition)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/fol.py", line 242, in _check_name_not_defined
    raise exception(name, where[name])
tarski.errors.DuplicateFunctionDefinition: Duplicate definition of element "ite": "ite"
