***Started - reading and parsing pddl file ...***
***Finished reading and parsing pddl file after 0.180 seconds CPU time, 0.175 seconds wall-clock time***

***Started - preprocessing tarski problem ...***
***Finished preprocessing tarski problem after 0.001 seconds CPU time, 0.001 seconds wall-clock time***

***Started - grounding ...***
/tmp/tmppey_21di:62:12-13: error: syntax error, unexpected (

/tmp/tmppey_21di:63:36-37: error: syntax error, unexpected (

/tmp/tmppey_21di:64:44-45: error: syntax error, unexpected (

/tmp/tmppey_21di:65:59-60: error: syntax error, unexpected (

/tmp/tmppey_21di:67:26-27: error: syntax error, unexpected (

/tmp/tmppey_21di:68:49-50: error: syntax error, unexpected (

/tmp/tmppey_21di:69:45-46: error: syntax error, unexpected (

/tmp/tmppey_21di:71:34-35: error: syntax error, unexpected (

/tmp/tmppey_21di:72:42-43: error: syntax error, unexpected (

/tmp/tmppey_21di:73:57-58: error: syntax error, unexpected (

/tmp/tmppey_21di:75:25-26: error: syntax error, unexpected (

/tmp/tmppey_21di:76:50-51: error: syntax error, unexpected (

/tmp/tmppey_21di:77:47-48: error: syntax error, unexpected (

/tmp/tmppey_21di:79:50-51: error: syntax error, unexpected (

/tmp/tmppey_21di:80:49-50: error: syntax error, unexpected (

/tmp/tmppey_21di:81:54-55: error: syntax error, unexpected (

/tmp/tmppey_21di:83:48-49: error: syntax error, unexpected (

/tmp/tmppey_21di:84:49-50: error: syntax error, unexpected (

/tmp/tmppey_21di:85:54-55: error: syntax error, unexpected (

*** ERROR: (gringo): grounding stopped because of errors
Traceback (most recent call last):
  File "brfs.py", line 60, in <module>
    main( sys.argv[1], sys.argv[2], sys.argv[3] )
  File "brfs.py", line 15, in main
    ground_generate_task( domain_file, problem_file, task )
  File "/home/anubhav-cs/Documents/Research_Project/anubhav-research/LAPKT-public/planners/brfs-tarski/tarski_parser/tarski_util.py", line 185, in ground_generate_task
    reachable_action_params =   copy.deepcopy( grounding.ground_actions())
  File "/media/anubhav-cs/SSD256/Applications/tarski/src/tarski/grounding/lp_grounding.py", line 39, in ground_actions
    model = self._solve_lp()
  File "/media/anubhav-cs/SSD256/Applications/tarski/src/tarski/grounding/lp_grounding.py", line 50, in _solve_lp
    model_filename = run_clingo(lp)
  File "/media/anubhav-cs/SSD256/Applications/tarski/src/tarski/reachability/clingo_wrapper.py", line 26, in run_clingo
    raise ExternalCommandError("Gringo exited with code {}".format(retcode))
tarski.errors.ExternalCommandError: Gringo exited with code 1
